<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DevExpress.Blazor.PdfViewer" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.Document.Processor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.Drawing.Skia" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Api.EFCore.All" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Chart" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Chart.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.CodeAnalysis" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.ConditionalAppearance" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Dashboards" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Dashboards.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Dashboards.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.FileAttachment.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.FileAttachment.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.MultiTenancy.AspNetCore.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.MultiTenancy.Blazor.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.MultiTenancy.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.MultiTenancy.Win.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Notifications" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Notifications.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Objects" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Office" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Office.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Office.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.PivotChart" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.PivotChart.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.PivotGrid" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.PivotGrid.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.ReportsV2" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.ReportsV2.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.ReportsV2.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Scheduler" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Scheduler.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Scheduler.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Security.AspNetCore.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Security.EFCore.Extensions.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.TreeListEditors" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.TreeListEditors.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Validation" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Validation.Blazor" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Validation.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.ViewVariantsModule" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Win" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.ExpressApp.Win.Design" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.Persistent.Base" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.Persistent.BaseImpl.EFCore" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.RichEdit.Export" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.Win.Design" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="DevExpress.Win.Map" Version="25.1.1-alpha-25115" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="8.0.91" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="6.9.0" />
    <PackageVersion Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>
</Project>