<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>ExpressApp.ico</ApplicationIcon>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest;Test</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <NoWarn>1701;1702;NU1507</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <NoWarn>1701;1702;NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Controllers\Order\ShipmentDetailController.cs" />
    <Compile Update="Features\Customers\CustomerGridView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Features\Customers\CustomerLayoutView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Features\Customers\CustomerStoreView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Features\Employees\EmployeesLayoutView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Features\Orders\OrderDetailView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Features\Orders\OrderGridView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Features\Products\ProductCardView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Editors\ColumnViewUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="DevExpress.ExpressApp.ListView" Alias="ListView" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Model.xafml" />
    <None Remove="Images\Logo.svg" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Model.xafml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\Logo.svg" />
    <EmbeddedResource Include="Images\SplashScreenImage.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp" />
    <PackageReference Include="DevExpress.ExpressApp.Chart.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Dashboards.Win" />
    <PackageReference Include="DevExpress.ExpressApp.EFCore" />
    <PackageReference Include="DevExpress.ExpressApp.FileAttachment.Win" />
    <PackageReference Include="DevExpress.ExpressApp.MultiTenancy.Win.EFCore" />
    <PackageReference Include="DevExpress.ExpressApp.Notifications.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Office.Win" />
    <PackageReference Include="DevExpress.ExpressApp.PivotChart.Win" />
    <PackageReference Include="DevExpress.ExpressApp.PivotGrid.Win" />
    <PackageReference Include="DevExpress.ExpressApp.ReportsV2.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Scheduler.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Security.EFCore.Extensions.Win" />
    <PackageReference Include="DevExpress.ExpressApp.TreeListEditors.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Validation.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Win" />
    <PackageReference Include="DevExpress.ExpressApp.Win.Design" />
    <PackageReference Include="DevExpress.Win.Map" />
    <PackageReference Include="DevExpress.Persistent.Base" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.EFCore" />
    <PackageReference Include="DevExpress.RichEdit.Export" />
    <PackageReference Include="DevExpress.Win.Design" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OutlookInspired.Module\OutlookInspired.Module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>